[build]
  publish = "public"

# Halaman Admin Shortener Biasa
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Halaman Generator Link Masking FB
[[redirects]]
  from = "/masking"
  to = "/masking.html"
  status = 200

[[redirects]]
  from = "/api/shorten"
  to = "/.netlify/functions/shorten"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/stats"
  status = 200

# Redirect Link Masking FB (/masking/slug)
[[redirects]]
  from = "/masking/:code"
  to = "/.netlify/functions/redirect?code=:code"
  status = 200

# Redirect Link Pendek Biasa (/slug)
[[redirects]]
  from = "/:code"
  to = "/.netlify/functions/redirect?code=:code"
  status = 200
